//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Clientes
    {
        public int ClienteID { get; set; }
        public string ClienteNome { get; set; }
        public string ClienteCPF { get; set; }
        public Nullable<System.DateTime> ClienteNascimento { get; set; }
        public string ClientePeso { get; set; }
        public string ClienteUF { get; set; }
    }
}
