CREATE DATABASE [gtDB]  (EDITION = 'Standard', SERVICE_OBJECTIVE = 'S0', MAXSIZE = 250 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO

ALTER DATABASE [gtDB] SET COMPATIBILITY_LEVEL = 140
GO

ALTER DATABASE [gtDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [gtDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [gtDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [gtDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [gtDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [gtDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [gtDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [gtDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [gtDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [gtDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [gtDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [gtDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [gtDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [gtDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [gtDB] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [gtDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [gtDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [gtDB] SET  MULTI_USER 
GO

ALTER DATABASE [gtDB] SET ENCRYPTION ON
GO

ALTER DATABASE [gtDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [gtDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO

/*** Os scripts das configurações no escopo do banco de dados no Azure devem ser executados dentro da conexão de banco de dados de destino. ***/
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ADAPTIVE_JOINS = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_ONLINE = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_RESUMABLE = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET GLOBAL_TEMPORARY_TABLE_AUTO_DROP = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET ISOLATE_SECURITY_POLICY_CARDINALITY = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET LIGHTWEIGHT_QUERY_PROFILING = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

-- ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET OPTIMIZE_FOR_AD_HOC_WORKLOADS = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET VERBOSE_TRUNCATION_WARNINGS = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET XTP_PROCEDURE_EXECUTION_STATISTICS = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET XTP_QUERY_EXECUTION_STATISTICS = OFF;
GO

ALTER DATABASE [gtDB] SET  READ_WRITE 
GO


-------------------------------------------------------------------------------------------------------------------------
use gtDB
go

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Clientes](
	[ClienteID] [int] IDENTITY(1,1) NOT NULL,
	[ClienteNome] [nvarchar](50) NOT NULL,
	[ClienteCPF] [nvarchar](50) NOT NULL,
	[ClienteNascimento] [date] NULL,
	[ClientePeso] [decimal](15, 2) NULL,
	[ClienteUF] [int] NOT NULL,
 CONSTRAINT [PK__Clientes__3214EC2747168409] PRIMARY KEY CLUSTERED 
(
	[ClienteID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Estados](
	[EstadoID] [int] NOT NULL,
	[EstadoNome] [varchar](255) NULL,
	[EstadoSigla] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[EstadoID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_Clientes] AS
SELECT 
	ClienteID,
    ClienteNome,
    ClienteCPF,
	ClienteNascimento,
    replace(convert(varchar,ClientePeso),'.',',') + ' Kg' as 'ClientePeso',
    e.EstadoNome as ClienteUF
FROM Clientes c
JOIN ESTADOS e ON e.EstadoID = c.ClienteUF
GO

